function [row,col] = ltln2SARrowcol(TC, R, lat, lon)
%LTLN2SARROWCOL Usefult to do the back-geocoding, convert a lat, lon couple
%to a row, col couple.
%   Inputs:
%           - TC is the Nlat x Nlon x 2 file generated by SNAP containing
%           the geocoding procedure
%           - R geocoding reference of the DEM
%           - lat, lon the two coordinates


% Target coordinate (lat, long)
point = [lat,lon];
[point_row,point_col] = latlon2pix(R,point(1),point(2));

% Range pixel
row=TC(round(point_row),round(point_col),1);

% Azimuth pixel
col=TC(round(point_row),round(point_col),2);


end

